# Generated by Django 4.2.2 on 2023-06-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifacts',
            name='is_published',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='artifacts',
            name='time_create',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='artifacts',
            name='time_update',
            field=models.BooleanField(blank=True),
        ),
    ]
