# Generated by Django 4.2.2 on 2023-06-09 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Artifacts', '0004_alter_artifacts_options_alter_sets_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifacts',
            name='content',
        ),
        migrations.AddField(
            model_name='artifacts',
            name='history',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifacts',
            name='stats',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
