# Generated by Django 4.2.2 on 2023-06-09 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Artifacts', '0005_remove_artifacts_content_artifacts_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifacts',
            name='price',
            field=models.IntegerField(default=8000),
            preserve_default=False,
        ),
    ]
